import express from "express";
import cors from "cors";
import crypto from "crypto";
import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const app=express(); app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||5000, ADMIN_ID=process.env.ADMIN_ID||"admin", ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"Anu@1234";
const sessions=new Map(); const here=path.dirname(fileURLToPath(import.meta.url)); const data=path.join(here,"../data"); fs.mkdirSync(data,{recursive:true});
const db=new Database(path.join(data,"anu-traders.db"));
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',price REAL NOT NULL,unit TEXT DEFAULT 'kg',stock REAL DEFAULT 0,featured INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_name TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,notes TEXT DEFAULT '',total REAL NOT NULL,status TEXT DEFAULT 'Pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,product_name TEXT,quantity REAL,unit TEXT,price REAL,subtotal REAL);`);
if(!db.prepare("SELECT COUNT(*) c FROM products").get().c){const p=[["Premium Ponni Rice","Rice","Clean, polished Ponni rice for everyday meals.",68,"kg",500,1],["Idli Rice","Rice","Quality rice for soft South Indian idlis.",54,"kg",350,1],["Raw Rice","Rice","Fresh raw rice with consistent grain quality.",52,"kg",420,0],["Wheat","Cereals","Clean whole wheat grains.",48,"kg",300,1],["Maize","Cereals","Good-quality maize.",32,"kg",250,0],["Ragi","Millets","Nutritious finger millet.",62,"kg",180,1],["Pearl Millet","Millets","Fresh pearl millet.",45,"kg",160,0],["Foxtail Millet","Millets","Premium foxtail millet.",95,"kg",120,1],["Green Gram","Pulses","Clean whole green gram.",118,"kg",140,0],["Black Gram","Pulses","Premium black gram.",132,"kg",100,0],["Toor Dal","Pulses","Everyday cooking dal.",145,"kg",160,1]];const s=db.prepare("INSERT INTO products(name,category,description,price,unit,stock,featured) VALUES(?,?,?,?,?,?,?)");db.transaction(()=>p.forEach(x=>s.run(...x)))();}
const auth=(req,res,next)=>{const t=req.get("Authorization")?.replace(/^Bearer\s+/i,"");const s=t&&sessions.get(t);if(!s||s<Date.now())return res.status(401).json({error:"Admin login required"});next()};
app.get("/api/health",(_,r)=>r.json({ok:true}));
app.get("/api/products",(_,r)=>r.json(db.prepare("SELECT * FROM products ORDER BY featured DESC,name").all()));
app.post("/api/admin/login",(req,r)=>{if(req.body?.id!==ADMIN_ID||req.body?.password!==ADMIN_PASSWORD)return r.status(401).json({error:"Invalid admin ID or password"});const t=crypto.randomBytes(24).toString("hex");sessions.set(t,Date.now()+8*60*60*1000);r.json({token:t})});
app.post("/api/admin/logout",auth,(req,r)=>{const t=req.get("Authorization")?.replace(/^Bearer\s+/i,"");sessions.delete(t);r.json({ok:true})});
const getOrder=id=>{const o=db.prepare("SELECT id,customer_name customerName,phone,address,notes,total,status,created_at createdAt FROM orders WHERE id=?").get(id);if(o)o.items=db.prepare("SELECT product_name name,quantity,unit,price,subtotal FROM order_items WHERE order_id=?").all(id);return o};
app.post("/api/orders",(req,r)=>{const {customerName,phone,address,notes="",items}=req.body||{};if(!customerName||!phone||!address||!Array.isArray(items)||!items.length)return r.status(400).json({error:"Customer details and at least one item are required"});try{const result=db.transaction(()=>{let total=0;const rows=items.map(i=>{const p=db.prepare("SELECT * FROM products WHERE id=?").get(i.productId),q=Number(i.quantity);if(!p||q<=0||q>p.stock)throw Error(`Invalid product or insufficient stock`);const subtotal=p.price*q;total+=subtotal;return {p,q,subtotal}});const o=db.prepare("INSERT INTO orders(customer_name,phone,address,notes,total) VALUES(?,?,?,?,?)").run(customerName,String(phone).trim(),address,notes,total);for(const x of rows){db.prepare("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit,price,subtotal) VALUES(?,?,?,?,?,?,?)").run(o.lastInsertRowid,x.p.id,x.p.name,x.q,x.p.unit,x.p.price,x.subtotal);db.prepare("UPDATE products SET stock=stock-? WHERE id=?").run(x.q,x.p.id)}return {id:o.lastInsertRowid,total}})();r.status(201).json({orderId:result.id,total:result.total})}catch(e){r.status(400).json({error:e.message})}});
app.get("/api/orders/:id",(req,r)=>{const o=getOrder(req.params.id);if(!o||o.phone!==String(req.query.phone||"").trim())return r.status(404).json({error:"Order not found. Check the order number and phone number."});r.json(o)});
app.get("/api/admin/orders",auth,(_,r)=>r.json(db.prepare("SELECT id,customer_name customerName,phone,address,notes,total,status,created_at createdAt FROM orders ORDER BY id DESC").all().map(o=>({...o,items:db.prepare("SELECT product_name name,quantity,unit,price,subtotal FROM order_items WHERE order_id=?").all(o.id)}))));
app.patch("/api/admin/orders/:id",auth,(req,r)=>{const allowed=["Pending","Confirmed","Packed","Delivered","Cancelled"];if(!allowed.includes(req.body?.status))return r.status(400).json({error:"Invalid status"});const x=db.prepare("UPDATE orders SET status=? WHERE id=?").run(req.body.status,req.params.id);if(!x.changes)return r.status(404).json({error:"Order not found"});r.json(getOrder(req.params.id))});
app.listen(PORT,()=>console.log(`Anu Traders API running on http://localhost:${PORT}`));